[package]
name = "rudf"
version = "0.0.1"
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
license = "MIT/Apache-2.0"
readme = "../README.md"
keywords = ["RDF"]
repository = "https://github.com/Tpt/rudf"
description = """
An RDF library in Rust
"""
build = "build.rs"

[badges]
travis-ci = { repository = "Tpt/rudf" }

[dependencies]
error-chain = "0.12"
lazy_static = "1"
rocksdb = "0.10"
url = "1"
uuid = { version = "0.6", features = ["v4"] }
bzip2 = "0.3"
byteorder = "1"

[build-dependencies]
peg = "0.5"

[dev-dependencies]
reqwest = "0.8"