[package]
name = "oxigraph_server"
version = "0.1.1"
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/oxigraph/oxigraph"
description = """
SPARQL server based on Oxigraph
"""
edition = "2018"

[dependencies]
argh = "0.1"
async-std = { version = "1", features = ["attributes"] }
async-h1 = "2"
http-client = { version = "4", features = ["h1_client"] }
http-types = "2"
oxigraph = { version = "0.1", path="../lib", features = ["rocksdb"] }
url = "2"
