[package]
name = "oxigraph_server"
version = "0.2.4"
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/oxigraph/oxigraph/tree/master/server"
homepage = "https://oxigraph.org/server/"
description = """
SPARQL server based on Oxigraph
"""
edition = "2018"

[features]
sled = ["oxigraph/sled"]
rocksdb = ["oxigraph/rocksdb"]
default = ["rocksdb"]

[dependencies]
argh = "0.1"
async-std = { version = "1", features = ["attributes"] }
async-h1 = "2"
clap = "2"
http-types = "2"
oxigraph = { version = "0.2", path="../lib", features = ["http_client"] }
rand = "0.8"
url = "2"
oxiri = "0.1"

[dev-dependencies]
tempfile = "3"
