[package]
name = "oxigraph_server"
version = "0.1.0"
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/oxigraph/oxigraph"
description = """
SPARQL server based on Oxigraph
"""
edition = "2018"

[dependencies]
oxigraph = {path = "../lib", features = ["rocksdb"] }
clap = "2"
rouille = "3"