[package]
name = "rudf_server"
version = "0.1.0"
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/Tpt/rudf"
description = """
Rudf based SPARQL server
"""
edition = "2018"

[dependencies]
rudf = {path = "../lib", features=["rocksdb"]}
clap = "2"
rouille = "3"