[package]
name = "oxigraph_server"
version = "0.3.0-dev"
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/oxigraph/oxigraph/tree/master/server"
homepage = "https://oxigraph.org/server/"
description = """
SPARQL server based on Oxigraph
"""
edition = "2021"

[dependencies]
oxhttp = "0.1"
clap = "2"
oxigraph = { version = "0.3.0-dev", path = "../lib", features = ["http_client"] }
rand = "0.8"
url = "2"
oxiri = "0.1"
