[package]
name = "oxigraph_testsuite"
version = "0.1.0"
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/oxigraph/oxigraph"
description = """
Implementation of W3C testsuites for Oxigraph
"""
edition = "2018"
publish = false

[dependencies]
anyhow = "1"
chrono = "0.4"
lazy_static = "1"
oxigraph = { path = "../lib" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "sparql_query"
harness = false