name: Nightly artifacts

on:
  push:
    branches:
      - master

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: rustup update
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: python -m venv python/venv
      - run: source python/venv/bin/activate && pip install --upgrade 'maturin~=0.12' sphinx
      - run: source venv/bin/activate && maturin develop
        working-directory: ./python
      - run: source ../venv/bin/activate && sphinx-build -M doctest . build
        working-directory: ./python/docs
      - run: source ../venv/bin/activate && sphinx-build -M html . build
        working-directory: ./python/docs
      - uses: actions/checkout@v2
        with:
          repository: oxigraph/oxigraph.github.io
          path: website
          token: ${{ secrets.FULL_ACCESS_TOKEN }}
      - run: rm -rf ./website/pyoxigraph/latest && mkdir -p ./website/pyoxigraph/latest && cp -r ./python/docs/build/html/* ./website/pyoxigraph/latest/
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Updates pyoxigraph documentation"
          git push
        working-directory: ./website

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: docker/metadata-action@v3
        id: docker_meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: nightly
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: server/Dockerfile
          pull: true
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
