name: build

on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update
      - run: rustup component add clippy
      - run: cargo clippy --all --all-targets

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - run: rustup update
    - run: cargo build
    - run: cargo test --verbose --all --all-features --exclude oxigraph_python
      env:
        RUST_BACKTRACE: 1

  js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update
      - run: cargo install wasm-pack
      - run: npm install
        working-directory: ./js
      - run: npm test
        working-directory: ./js

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update
      - uses: actions/setup-python@v2
        with:
          python-version: 3.5
      - run: python -m venv python/tests/venv
      - run: source python/tests/venv/bin/activate && pip install --upgrade pip maturin
      - run: source tests/venv/bin/activate && maturin develop
        working-directory: ./python
      - run: source venv/bin/activate && python -m unittest
        working-directory: ./python/tests
